import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/ui/header";
import Footer from "@/ui/footer";

const inter = Inter({ subsets: ["latin"] });

type MainStyles = {
  display: string;
  flexDirection: "column";
  justifyContent: string;
  alignItems: string;
  padding: string;
  minHeight: string;
};

export const metadata: Metadata = {
  title: "Landing page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mainStyles: MainStyles = {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "6rem",
    minHeight: "100vh",
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main style={mainStyles}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
